# Doc : https://github.com/Nordix/xcluster-cni
# Source : https://raw.githubusercontent.com/Nordix/xcluster-cni/master/xcluster-cni.yaml
# Version : latest
# Date : 2020-08-26
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xcluster-cni
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xcluster-cni
rules:
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - list
      - get
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xcluster-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xcluster-cni
subjects:
- kind: ServiceAccount
  name: xcluster-cni
  namespace: kube-system                      
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xcluster-cni
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: xcluster-cni
  template:
    metadata:
      namespace: kube-system
      labels:
        app: xcluster-cni
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: xcluster-cni
      serviceAccount: xcluster-cni
      hostNetwork: true
      containers:
      - name: xcluster-cni
        image: registry.nordix.org/cloud-native/xcluster-cni:latest
        lifecycle:
          preStop:
           exec:
             command: ["/xcluster-cni.sh", "stop"]
        env:
          - name: K8S_NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          # TUNNEL_MODE=None|sit
          - name: TUNNEL_MODE
            value: "sit"
          # Include all :'s, example; "1000:2::" -> 1000:2::192.169.1.2
          - name: IPV6_PREFIX
            value: ""
        securityContext:
          privileged: true
        volumeMounts:
         - mountPath: /cni/bin
           name: cni-bin-dir
           readOnly: false
         - mountPath: /cni/net.d
           name: cni-net-dir
           readOnly: false
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
